spring.application.name=benficiary
spring.datasource.url=jdbc:mysql://localhost:3306/bankbeneficiary
spring.datasource.username=root
spring.datasource.password=test123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
